services:
  db:
    image: postgres:latest
    restart: unless-stopper
    ports:
      - ${WEB_SOCKET_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WEB_SOCKET_DATABASE_USER}
      POSTGRES_PASSWORD: ${WEB_SOCKET_DATABASE_PASSWORD}
      POSTGRES_DB: ${WEB_SOCKET_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
